drop table if exists booking CASCADE;
drop table if exists conference_room CASCADE;
create table booking (id bigint generated by default as identity, end_time timestamp, number_of_people integer not null, start_time timestamp, room_id bigint, primary key (id));
create table conference_room (id bigint not null, capacity integer, name varchar(255), primary key (id));
create table maintenance_time (id bigint generated by default as identity, end_time time, start_time time, primary key (id));
alter table booking add constraint FKd2e82msvte4h2lj72tghgmqcu foreign key (room_id) references conference_room;

-- Insert Conference Rooms
INSERT INTO conference_room (id, capacity, name)
VALUES (1, 3, 'Amaze'),
       (2, 7, 'Beauty'),
       (3, 12, 'Inspire'),
       (4, 20, 'Strive');

-- Insert Maintenance Times for Room 'Amaze'
INSERT INTO maintenance_time (start_time, end_time)
VALUES ('09:00:00', '09:15:00'),
       ('13:00:00', '13:15:00'),
       ('17:00:00', '17:15:00');
